### PR TITLE
chore: update time dependency to fix builds against newer Rust versions

### PR DESCRIPTION
**Pull request by cole-h**

### CODE REVIEW

**Comment by cole-h** [comment]
Technically a duplicate of https://github.com/kbknapp/cargo-outdated/pull/397, but their commit message doesn't follow the "conventional commits" format specified in the contributing document.

**Review by beeb — APPROVED** [review]

**Review by jaztec — APPROVED** [review]

**Review by kpcyrd — APPROVED** [review]

**Comment by kbknapp** [comment]
Should be rolled up into #403

**Comment by kpcyrd** [comment]
Can we get a new release so this can be rolled out to users of Linux distributions? :)

**Comment by kbknapp** [comment]
> Can we get a new release so this can be rolled out to users of Linux distributions? :)

Once #406 merges there will be a new release.

**Pull request closed without merging**
