### PR TITLE
refactor: introduce `cargo` as a dependency

### LINKED ISSUE #20: Provide option to check build dependencies as well
Or perhaps make it the default?

### LINKED ISSUE #28: Support cargo workspaces
It would be nice to provide a flag to view outdated dependencies for the entire workspace.

### LINKED ISSUE #46: What does "RM" mean in the output?
```text
Name                                   Project Ver     SemVer Compat  Latest Ver
aho-corasick->memchr                      0.1.11            RM            RM
```

Might be nice to have this explained somewhere.

### LINKED ISSUE #49: cargo outdated just says 'RM' for everything.
Here's output from one of my projects ([`c-ares-resolver`](https://github.com/dimbleby/c-ares-resolver)):

```
$ cargo outdated
Name                        Project Ver  SemVer Compat  Latest Ver
bytes->byteorder               1.1.0          RM            RM
bytes->iovec                   0.1.0          RM            RM
conv->custom_derive            0.1.7          RM            RM
dns-parser                     0.7.0          RM            RM
dns-parser->byteorder          0.4.2          RM            RM
dns-parser->matches            0.1.6          RM            RM
dns-parser->quick-error        1.2.0          RM            RM
iovec->libc                    0.2.29         RM            RM
iovec->winapi                  0.2.8          RM            RM
kernel32-sys->winapi           0.2.8          RM            RM
kernel32-sys->winapi-build     0.1.1          RM            RM
magenta->conv                  0.3.3          RM            RM
magenta->magenta-sys           0.1.1          RM            RM
magenta-sys->bitflags          0.7.0          RM            RM
mio->iovec                     0.1.0          RM            RM
mio->kernel32-sys              0.2.2          RM            RM
mio->lazycell                  0.5.1          RM            RM
mio->libc                      0.2.29         RM            RM
mio->log                       0.3.8          RM            RM
mio->magenta                   0.1.1          RM            RM
mio->magenta-sys               0.1.1          RM            RM
mio->miow                      0.2.1          RM            RM
mio->net2                      0.2.30         RM            RM
mio->slab                      0.3.0          RM            RM
mio->winapi                    0.2.8          RM            RM
miow->kernel32-sys             0.2.2          RM            RM
miow->net2                     0.2.30         RM            RM
miow->winapi                   0.2.8          RM            RM
miow->ws2_32-sys               0.2.1          RM            RM
net2->cfg-if                   0.1.2          RM            RM
net2->kernel32-sys             0.2.2          RM            RM
net2->libc                     0.2.29         RM            RM
net2->winapi                   0.2.8          RM            RM
net2->ws2_32-sys               0.2.1          RM            RM
tokio-core                     0.1.9          RM            RM
tokio-core->bytes              0.4.4          RM            RM
tokio-core->futures            0.1.14         RM            RM
tokio-core->iovec              0.1.0          RM            RM
tokio-core->log                0.3.8          RM            RM
tokio-core->mio                0.6.10         RM            RM
tokio-core->scoped-tls         0.1.0          RM            RM
tokio-core->slab               0.3.0          RM            RM
tokio-core->tokio-io           0.1.2          RM            RM
tokio-io->bytes                0.4.4          RM            RM
tokio-io->futures              0.1.14         RM            RM
tokio-io->log                  0.3.8          RM            RM
winapi                         0.2.8          RM            RM
ws2_32-sys                     0.2.1          RM            RM
ws2_32-sys->winapi             0.2.8          RM            RM
ws2_32-sys->winapi-build       0.1.1          RM            RM
```

#46 already has me covered for "I've no idea what RM even means", this issue says "surely that's not right?"

### LINKED ISSUE #50: doesn't work when dependency is in path
```
$ cargo outdated
error: Failed to run 'cargo update' with error 'did not exit successfully'
```

I saw this with [`c-ares`](https://github.com/dimbleby/rust-c-ares).  

I believe the difficulty is dealing with [this](https://github.com/dimbleby/rust-c-ares/blob/664f295e5c8d73a04babf23003dc66bcbe9e517e/Cargo.toml#L17): `cargo outdated` copies my `Cargo.toml` into a temporary directory but does not copy `c-ares-sys/Cargo.toml`.  That's why `cargo update` fails.

### PR DESCRIPTION
**Pull request by Frederick888**
So this is the version with `cargo` as a dependency, which tends to be a "more native" one as suggested in rust-lang/cargo#4309.

Changes:
1. Introduces `cargo` as a dependency
0. Supports cargo workspaces (closes #28)
0. Supports embedded dependencies, see [issuecomment-320433502](https://github.com/kbknapp/cargo-outdated/issues/50#issuecomment-320433502) (fixes #50)
0. Replaces `RM` with `Removed` (closes #46)
0. Build/development dependencies are included (closes #20, fixes #49)
0. Target-specific dependencies are included
0. Feature-related `--all-features` `--features` `--no-default-features` as other cargo subcommands
0. New output format

There ~might~ should still be some bugs and some implementations are a bit silly, but it's already fine to me for a new release. And by the way @kbknapp, is it ok to add me to the author list as well?

Example 1
---
Run `cargo outdated -r openssl` against rust-lang/cargo@a60d185c (0.20.0)
```
Name                      Project  Compat   Latest   Kind    Platform
gdi32-sys->winapi         0.2.8    Removed  Removed  Normal  ---
gdi32-sys->winapi-build   0.1.1    Removed  Removed  Build   ---
openssl                   0.9.13   0.9.15   0.9.15   Normal  cfg(unix)
openssl->libc             0.2.23   0.2.29   0.2.29   Normal  ---
openssl->openssl-sys      0.9.13   0.9.15   0.9.15   Normal  ---
openssl-sys->gcc          0.3.50   0.3.51   0.3.51   Build   ---
openssl-sys->gdi32-sys    0.2.0    Removed  Removed  Normal  cfg(windows)
openssl-sys->libc         0.2.23   0.2.29   0.2.29   Normal  ---
openssl-sys->user32-sys   0.2.0    Removed  Removed  Normal  cfg(windows)
user32-sys->winapi        0.2.8    Removed  Removed  Normal  ---
user32-sys->winapi-build  0.1.1    Removed  Removed  Build   ---
```

Example 2
---
Run `cargo outdated -d 3` against Manishearth/rust-clippy@681a3031b5128e6cf42e6195c51bd3fd671c5731
```
Name                    Project  Compat  Latest   Kind         Platform
clippy_lints->semver    0.6.0    ---     0.7.0    Normal       ---
duct                    0.8.2    ---     0.9.1    Development  ---
duct->error-chain       0.8.1    ---     Removed  Normal       ---
duct->shared_child      0.2.1    ---     0.3.2    Normal       ---
error-chain->backtrace  0.3.2    ---     Removed  Normal       ---
```

Example 3
---
Run `cargo outdated --features color` against https://gist.github.com/Frederick888/306bf41c0aef2f4ec409add082ee5d0b
```
Name             Project  Compat  Latest   Kind         Platform
clap             2.20.0   2.20.5  2.26.0   Normal       ---
clap->bitflags   0.7.0    ---     0.9.1    Normal       ---
clap->libc       0.2.18   0.2.29  Removed  Normal       ---
clap->term_size  0.2.1    0.2.3   0.3.0    Normal       ---
clap->vec_map    0.6.0    ---     0.8.0    Normal       ---
num_cpus         1.6.0    ---     1.6.2    Development  ---
num_cpus->libc   0.2.18   0.2.29  0.2.29   Normal       ---
pkg-config       0.3.8    0.3.9   0.3.9    Build        ---
term             0.4.5    ---     0.4.6    Normal       ---
term_size->libc  0.2.18   0.2.29  0.2.29   Normal       cfg(not(target_os = "windows"))
```

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for working on this @Frederick888!

I ran this locally and got a bunch of lines that look like:

```
url->percent-encoding   1.0.0    ---     Removed  Normal  ---
```

This was inside of rustup.rs, but I was wondering if maybe you know what's going on there? (specifically the "Removed" bit)

**Comment by Frederick888** [comment]
@alexcrichton It means that a node in the dependency tree is removed after an update.

In the case of `rustup`, I deem it's because after the semver requirements of module `download` are replaced by wildcards, `hyper` is updated to `1.11.x` and `url` is no longer a dependency of `hyper`, hence the whole sub tree is marked as `Removed`

**Comment by alexcrichton** [comment]
Ah ok! 👍

**Comment by Frederick888** [comment]
@alexcrichton Actually I wonder whether I could replace [`Manifest`](https://github.com/kbknapp/cargo-outdated/blob/d056fd0556601d28bba8f71a6b564a6b34382bc3/src/cargo_ops/mod.rs#L13) with [`TomlManifest`](https://docs.rs/cargo/0.20.0/cargo/util/toml/struct.TomlManifest.html) or not to modify the semver requirements as the fields of [`TomlManifest`](https://docs.rs/cargo/0.20.0/cargo/util/toml/struct.TomlManifest.html) are private...

Is it possible to modify the manifest through `cargo` and write it back?

**Comment by alexcrichton** [comment]
Unfortunately writing back a manifest may not be possible right now with Cargo's public API, but if you've got suggestion for modifying Cargo's API we're always more than willing to take PRs!

**Comment by SergioBenitez** [comment]
I tried running this on a few of my projects. First, there appears to be some issues running this against Rocket. When I run this inside Rocket's `lib/`, I get:

```
Rocket/lib ❯ cargo outdated
error: failed to read `/var/folders/jg/0xyyp7ys2752_121dvfp4nrm0000gn/T/cargo-outdated.RAsybF6nEGgy/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

I then tried running this against a project with some outdated dependencies:

```toml
rocket = "0.2.2"
rocket_codegen = "0.2.2"
rand = "0.3"
```

I was expecting for the output to contain three lines, one for each outdated dependency, but instead the output contained 87 (!) lines, apparently one for each outdated _transitive_ dependency. This seems like bad default behavior. There's nothing I can do about outdated transitive dependencies, so showing me those as outdated by default only makes it hard to see what I _can_ control. I suggest  showing all outdated transitive dependencies optional and disabled by default. Perhaps by default you can display a message saying something like, "Outdated transitive dependencies detected. For the full list, run `cargo outdated --transitive`."

**Comment by Keats** [comment]
Since it was generally accepted to add a native `cargo outdated` to Cargo (https://github.com/rust-lang/cargo/issues/4309), would it make more sense to do a PR on Cargo directly?

I would also like to hide the transitive dependencies completely by default and maybe add a flag to show them: it just pollutes the output imo.
Is it possible to get the repo url from the manifest/Cargo for a crate? I use that all the time in `yarn` output to look at the changelog before updating.

Nitpick: `Project` -> `Current` for the header

**Comment by Frederick888** [comment]
@SergioBenitez Ah, I think I know what the problem is. Before using `cargo` the `lib/` was treated as the project root but now `cargo` finds the real project root automatically. I'd try to make some time to fix it.

In terms of the default behaviour, showing the transitive dependencies is actually the default one of some other package managers as well, e.g. `composer`. But personally I reckon it's more intuitive to print only the direct ones by default. However my concern is that this could potentially introduce some inconsistencies. For example, if the users selects another root via `-r`, I deem that transitive dependencies should then be shown in this case. Sometimes too many defaults and hypotheses from developers would make it unwieldy instead.

---
@Keats I think it's still a bit early to merge this function to the development cycle of `cargo`. It's currently much too immature and need more feedback from users to be stabilised.

**Comment by Frederick888** [comment]
@SergioBenitez I have just pushed a fixed to your issue here. Could you give it a try?

**Comment by mitskevich** [comment]
I'm getting following error with freshly compiled `feature/cargo-depend` branch:

```
$ RUST_BACKTRACE=1 cargo outdated -v
  Parsing... current workspace
Resolving... current workspace
  Parsing... compat workspace
thread 'main' panicked at 'byte index 55 is out of bounds of `/Users/sam/Development/project/tokio-modbus`', src/libcore/str/mod.rs:2171:8
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_new
   4: std::panicking::begin_panic_fmt
   5: core::panicking::panic_fmt
   6: core::str::slice_error_fail
   7: cargo_outdated::cargo_ops::temp_project::manifest_paths::manifest_paths_recursive
   8: cargo_outdated::cargo_ops::temp_project::manifest_paths::manifest_paths_recursive
   9: cargo_outdated::cargo_ops::temp_project::TempProject::from_workspace
  10: cargo_outdated::execute
  11: cargo_outdated::main
  12: main
```

My Cargo.toml:
```
[package]
name = "operator"
version = "0.1.0"

[dependencies]
bodyparser = "0.7"
bytes = "0.4"
chrono = { version = "0.4", features = ["serde"] }
clap = "2.23"
colored = "1.4"
decimal = "1.0"
env_logger = "0.4"
error-chain = "0.10"
eui48 = "0.3"
futures = "0.1"
futures-cpupool = "0.1"
iron = "0.5"
log = "0.3"
num = "0.1"
postgres = { version = "0.15", features = ["with-chrono"] }
postgres-derive = "0.3"
r2d2 = "0.7"
r2d2_postgres = "0.13"
rand = "0.3"
router = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tera = "0.10"
time = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-modbus = { path="../tokio-modbus" }
# change back to version once 0.1.2 is out
tokio-proto = { git = "https://github.com/tokio-rs/tokio-proto", rev = "8fb8e482dcd55cf02ceee165f8e08eee799c96d3" }
tokio-service = "0.1"
tokio-timer = "0.1"
toml = "0.4"
percent-encoding = "1.0"
```

System: MacOS Sierra
Cargo: cargo 0.21.0 (5b4b8b2ae 2017-08-12)
Rustc: rustc 1.20.0 (f3d6973f4 2017-08-27)

**Comment by SergioBenitez** [comment]
@Frederick888 Okay, that seemed to fix the problem. A couple of notes/questions, however:

  1. What does "supporting workspaces" mean?

     My expectation was that I could run `cargo outdated` at the root of a workspace and have the tool check all dependencies used by any crate in the workspace. Instead, I get: "error: manifest path `/Rocket/Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace". Is there a way to get the functionality I'm looking for? If not, what workspace support has been added?

  2. Why does running `cargo outdated` result in crates being downloaded?

     When I run `cargo outdated`, the tool downloads some crates. What's going on there? Why is this happening? Maybe there's a good reason, and if there is, some message indicating the reason should be printed. 

  3. `--all-features` should be enabled by default

     Because I'm using this tool to find outdated dependencies, it's very unlikely that I somehow don't care about optional dependencies. Much like my previous comment about `--depth 1` being the default, I think `--all-features` should be the default as well. It's what I'm using the tool for, and the tool shouldn't make it harder to get that done.

**Comment by Frederick888** [comment]
@mitskevich Thanks for the fix. I modified it a bit and have pushed a new commit here.

The new error seems to be caused by an uncopied manifest file, i.e. `tokio-modbus/Cargo.toml` in your case. But I wasn't able to reproduce the error locally. I tried it on [`Rocket`](https://github.com/SergioBenitez/Rocket/blob/master/lib/Cargo.toml#L42), which has also such a dependency and it worked totally fine. Is it possible for you make a more complete example?

---
@SergioBenitez 

1. You still need to enter the specific crate root to check the updates. Previously `cargo-outdated` would complete ignore the workspace and member stuff so it crashed in such scenarios. But yeah, it makes sense to loop through all the members and possibly even better to have a `Member` column in the output.

0. `cargo-outdated` was designed to run `cargo update` against the project to check updates so it's `cargo update` that's downloading the crates. Maybe it doesn't sound quite programmatic but the idea originally from @kbknapp is fairly concise and works great. Personally I'm not very familiar with the internal stuff of `cargo` and perhaps there's a better way to query the registry...? (it's time to @alexcrichton lol) But definitely the messages from `cargo update` should not be suppressed when `-v` is used. I'd fix it asap.

0. Great suggestion, thanks! And for the default depth, actually there is a discussion going on here: #53

**Comment by Keats** [comment]
> 1. You still need to enter the specific crate root to check the updates. Previously cargo-outdated would complete ignore the workspace and member stuff so it crashed in such scenarios. But yeah, it makes sense to loop through all the members and possibly even better to have a Member column in the output.

How about changing grouping by member? An output like the following for one of my projects:

```
site
================
Name          Current  Compat  Latest    Kind         Platform
clap             2.20.0     2.20.5    2.26.0   Normal       ---

rendering
================
Name          Current  Compat  Latest    Kind         Platform
clap             2.20.0     2.20.5    2.26.0   Normal       ---
```
Adding a column doesnt necessarily make sense as some members might have the same packages with different versions for some reasons

**Comment by Frederick888** [comment]
@Keats That's an awesome idea! I like it.

**Comment by mitskevich** [comment]
@Frederick888 Here is an example that consistently breaks latest version of `cargo outdated` for me (with the same error as in my previous comment): https://github.com/mitskevich/cargo-outdated-example. Error is happening only when I run it in `./modbus-operator` project folder. When I remove `tokio-modbus` dependency, `cargo outdated` works correctly.

If you will not be able to reproduce it, please let me know, I'll check what is happening in more details later.

**Comment by Frederick888** [comment]
@mitskevich Ah, I see. Currently a `Cargo.toml` would be copied to the temporary directory if:

1. it's in the sub-folder of the working one, e.g. a relative path `foo_bar = { path = "local_dependency/foo_bar" }` dependency
0. it's in the same workspace of the working one

Otherwise there's simply no relationship between `modbus-operator` and `tokio-modbus` in your case, hence `cargo` won't take it as a member of the project. I suggest you create a virtual manifest in their parent directory, or use absolute path instead for now. And this does warn me of some other possible issues, e.g. `path = "local_dependency/../../../../../somewhere"`.

Perhaps I should resolve all the relative paths to absolute ones first so all such craps could be gone.

**Comment by Frederick888** [comment]
@mitskevich I think your issue should be fixed by a8491e0. Could you please check it?

**Comment by mitskevich** [comment]
@Frederick888 Yep, `cargo-depend` branch build works correctly on all my projects now. Thanks!

**Comment by Frederick888** [comment]
So as it stands now, most of the discovered "bugs" have been fixed in this PR. Since other ongoing discussions in this thread are basically related to improvements and new features, I think I'd merge this PR, tag a new release (although I can't publish it to crates.io) and file independent issues for them. I would be a bit busy in the next one or two months and this could make it more friendly to potential PRs from others.

**Pull request merged**
