### PR TITLE
refactor: explicit tree structure

### PR DESCRIPTION
**Pull request by Frederick888**
Manually tested against several repos and it looked fine.

Notable changes are:
1. Using an explicit tree to handle the dependency tree
0. Now if a dependency is removed after an update, it will show `RM` for it
0. `clippy` was removed from the dependencies since previously it was mainly used for `Lockfile::get_updates()` but the method is gone now

Basically just refactoring, few functionality changes involved.

If you reckon there are no major issues with this PR maybe it's time to merge it and publish a new version @kbknapp :) Thanks

### CODE REVIEW

**Comment by kbknapp** [comment]
@Frederick888 I've removed homu from being required, so you should be able to merge this once the conflict is resolved

**Comment by Frederick888** [comment]
@kbknapp Cool, thanks.

**Comment by kbknapp** [comment]
@Frederick888 0.4.0 is out :wink:

**Comment by Frederick888** [comment]
@kbknapp Dope. Great thanks, buddy :sunglasses:

**Comment by jgulotta** [comment]
Thanks so much for the new version @Frederick888 @kbknapp! I use `cargo outdated` almost daily and found myself saying "I wonder how off it is this time". With this merge my only complaints are gone and the tool is pretty much perfect for my needs! :heart:

**Comment by kbknapp** [comment]
@Frederick888 did all the heavy lifting 😉

**Pull request merged**
