### PR TITLE
Updated the semver parsing to avoid un-parsable characters

### PR DESCRIPTION
**Pull request by deg4uss3r**
Creating a new PR to correct all occurrences of the rust TOML versioning shorthand that might exist and will break the semver parsing. 

Using the [Rust Cargo Doc](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html) for reference. 

Please let me know if there is anything else you can see that will break semver parsing. `*` in the version does get resolved before it is passed the `valid_latest_version()` function in my tests.

### CODE REVIEW

**Comment by deg4uss3r** [comment]
I also tried to do something like: 
```rust
let requirement_version = VersionReq::parse(&requirement).expect("Error could not parse requirement into a semantic version");
let requirement_channel = requirement_version.predicates[0].pre[0].to_string();
```

However, the struct fields in `VersionReq` are not public and I cannot compare them like so, also this might lead to bugs if there's a lot of predicates with different channels.

**Comment by kornelski** [comment]
Looks good. Can you rebase and/or squash it?

**Comment by deg4uss3r** [comment]
@kornelski let me know if I did the squash appropriately :)

**Comment by kornelski** [comment]
No, you did a regular merge. I'll squash it.

Next time try an app that visualizes commits, e.g. https://git-fork.com or `gitk --all`

**Pull request merged**
