### PR TITLE
[Feature Proposal] Use explicit trees to handle dependencies

### PR DESCRIPTION
**Pull request by Frederick888**
The dependency tree currently is handled by a `HashMap` of which the keys are package names. However this does not work very well from time to time since a single package may have multiple occurrences with different SemVer requirements (and some of them may even be removed after updated).

To resolve this issue, personally I think the most straightforward way is to use an explicit tree to store the dependencies as `cargo-outdated` is not actually SemVer-aware (and it's difficult to find out the SemVer requirements from dependencies without flooding https://crates.io/api).

Here I'm using a `HashMap<"package_name package_version", Rc<RefCell<Package>>>` to store all the nodes (packages) in the tree, and each node (package) has another `HashMap<"package_name", Weak<RefCell<Package>>` for its dependencies.

Not sure whether this is a good idea and frankly writing a tree in Rust is still quite challenging for me. It would be nice if I can get some mentoring.

### CODE REVIEW

**Comment by Frederick888** [comment]
@kbknapp This is still incomplete and actually I have more in mind, e.g. supporting Git dependencies, tree/json formatted output and etc. Still learning Rust but I think I can have some time to maintain this repo if you like.

**Comment by kbknapp** [comment]
@Frederick888 I apologise I've had absolutely Zero time lately! If you're still interested in helping to maintain this repo I'll add you!

**Comment by Frederick888** [comment]
@kbknapp Just closed the PR as I found a bug in it 😂. But it would be great if you could add me to the project and I'd try to fix it :)

**Comment by kbknapp** [comment]
Added :) welcome!

**Pull request closed without merging**
